### ISSUE TITLE
Cannot run JUnit Jupiter Tests - 4.0.0.M15

### ISSUE THREAD

**Issue by phillipuniverse** [spring-projects/sts4#71]
I had verified this working on 4.0.0-M11, looks like a regression in one of the milestones.

Whenever running a Junit 5 test, I get this stack trace in the console:

```java
java.lang.NoClassDefFoundError: junit/framework/ComparisonFailure
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.getFailedComparison(JUnit5TestListener.java:133) ~[.cp/:na]
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.notifyIfNotSuccessful(JUnit5TestListener.java:89) ~[.cp/:na]
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.executionFinished(JUnit5TestListener.java:71) ~[.cp/:na]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$3(TestExecutionListenerRegistry.java:77) ~[.cp/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51) ~[.cp/:na]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27) ~[.cp/:na]
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:77) ~[.cp/:na]
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56) ~[.cp/:na]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.reportDone(HierarchicalTestExecutor.java:141) ~[junit-platform-engine-1.1.1.jar:1.1.1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:84) ~[junit-platform-engine-1.1.1.jar:1.1.1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55) ~[junit-platform-engine-1.1.1.jar:1.1.1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43) ~[junit-platform-engine-1.1.1.jar:1.1.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170) [.cp/:na]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154) [.cp/:na]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90) [.cp/:na]
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209) [.cp/:na]
```

My project is extending from `spring-boot-starter-parent:2.0.4.RELEASE`. These are the relevant dependencies:

```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-junit-jupiter</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
    <exclusions>
        <!-- Excluding for conflict with JUnit Jupiter which is under a different groupId/artifactId -->
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

I removed the Jupiter dependencies to use JUnit 4 and the test worked appropriately (gave correct failure/success).

**Comment by martinlippert** [comment]
@phillipuniverse Can you double check this with a recent Eclipse 2018-09 RC build (e.g. from here: https://www.eclipse.org/downloads/packages/release/2018-09/rc1)? That would be awesome - just to make sure where to look for the underlying issue. Many many thanks!!!

**Comment by phillipuniverse** [comment]
As I'm not familiar with 'jupiter'. It would help if you can attach a full project that we can just import and try to run rather than just a pom snippet.

@kdvolder good idea, should have led with that. To be clear, JUnit Jupiter is the codename for JUnit 5.

I did a bit more investigation here, her was my methodology:

1. Download a new vanilla version of STS (the one I regularly use has a few other plugins)
2. Create a project from https://start.spring.io
3. Add the Junit 5 dependencies
4. Play around with tests

It seems that this only occurs when the test throws an exception that is otherwise unhandled.
[Here is a sample project](https://github.com/spring-projects/sts4/files/2370818/junit5-sts-failure.zip) that I imported into STS using File -> Import -> Existing Maven Projects.

Here is a screenshot of my results when running this test. My assumption is that the test should be red
<img width="1509" alt="screen shot 2018-09-11 at 6 51 36 am" src="https://user-images.githubusercontent.com/684275/45358638-ad76e080-b58f-11e8-9a7b-aa253794094f.png">


@martinlippert give me a few, I will try with that recent Eclipse RC1 build.

**Comment by phillipuniverse** [comment]
@martinlippert @kdvolder you guys are correct, it looks like this is a core Eclipse issue. To test, I:

1. Went to the link that @martinlippert posted
2. Downloaded "Eclipse IDE for Java EE Developers" (the macOS version)
3. Imported the same demo project from before
4. Ran the test with right-click -> Run As -> JUnit Test

Do you guys have a pointer to the best place to open this as a bug within Eclipse? I can probably find the general Bugzilla tracker, just curious if you guys have a suggestion.

Thanks again for your help!

**Comment by martinlippert** [comment]
Thanks for double checking this, much appreciated. I would report this against Eclipse JDT here: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT - would select "UI" as the component, I guess most of the JUnit support is done as part of the JDT UI project. If you file a bug, posting a reference to that here would be great, so that other users can find that.

**Comment by phillipuniverse** [comment]
Will do, thanks again!

**Comment by phillipuniverse** [comment]
To close the loop: Eclipse issue opened at https://bugs.eclipse.org/bugs/show_bug.cgi?id=538956. No need to comment any longer on this issue, discussion can continue there.
